{
 "title": "HTTP codes",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "HTTP codes 2xx",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",60s),\n  count(code) AS \"number of http codes\"\nFROM http_code\nWHERE\n  $__timeFilter(\"time\") AND\n  CAST(code AS TEXT) LIKE '2%'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "HTTP codes 4xx",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",60s),\n  count(code) AS \"number of http codes\"\nFROM http_code\nWHERE\n  $__timeFilter(\"time\") AND\n  CAST(code AS TEXT) LIKE '4%'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "HTTP codes 5xx",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",60s),\n  count(code) AS \"number of http codes\"\nFROM http_code\nWHERE\n  $__timeFilter(\"time\") AND\n  CAST(code AS TEXT) LIKE '5%'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}