{
 "title": "Seconds on sites",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "users", "query": "select id from public.user" }
  ]
 },
 "panels": [
  {
   "title": "Seconds on site \"widok1\" by user",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  exit_time AS \"time\",\n  time_spent\nFROM user_event, public.user\nWHERE\n  $__timeFilter(exit_time) AND\n  public.user.id = user_event.user_id AND public.user.id = [[users]] AND\n  site = 'podstrony/widok1'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Seconds on site \"widok2\" by user",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  exit_time AS \"time\",\n  time_spent\nFROM user_event, public.user\nWHERE\n  $__timeFilter(exit_time) AND\n  public.user.id = user_event.user_id AND public.user.id = [[users]] AND\n  site = 'podstrony/widok2'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Seconds on site \"widok3\" by user",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  exit_time AS \"time\",\n  time_spent\nFROM user_event, public.user\nWHERE\n  $__timeFilter(exit_time) AND\n  public.user.id = user_event.user_id AND public.user.id = [[users]] AND\n  site = 'podstrony/widok3'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Seconds spent on site \"widok4\" by user",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  exit_time AS \"time\",\n  time_spent\nFROM user_event, public.user\nWHERE\n  $__timeFilter(exit_time) AND\n  public.user.id = user_event.user_id AND public.user.id = [[users]] AND\n  site = 'podstrony/widok4'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Seconds spent on site \"widok1\"",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  exit_time AS \"time\",\n  time_spent\nFROM user_event\nWHERE\n  $__timeFilter(exit_time) AND\n  site = 'podstrony/widok1'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Seconds spent on site \"widok2\"",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  exit_time AS \"time\",\n  time_spent\nFROM user_event\nWHERE\n  $__timeFilter(exit_time) AND\n  site = 'podstrony/widok2'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Seconds spent on site \"widok3\"",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  exit_time AS \"time\",\n  time_spent\nFROM user_event\nWHERE\n  $__timeFilter(exit_time) AND\n  site = 'podstrony/widok3'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Seconds spent on site \"widok4\"",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  exit_time AS \"time\",\n  time_spent\nFROM user_event\nWHERE\n  $__timeFilter(exit_time) AND\n  site = 'podstrony/widok4'\nORDER BY 1"
    }
   ]
  }
 ]
}